export const CHAMPIONS_ITEM_OPTIONS = [
  "あついいわ",
  "イトケのみ",
  "いのちのたま",
  "ウタンのみ",
  "おうじゃのしるし",
  "おおきなねっこ",
  "オッカのみ",
  "オボンのみ",
  "オレンのみ",
  "かいがらのすず",
  "カゴのみ",
  "カシブのみ",
  "かたいいし",
  "きあいのタスキ",
  "きあいのハチマキ",
  "キーのみ",
  "きせきのタネ",
  "きれいなぬけがら",
  "ぎんのこな",
  "くろいてっきゅう",
  "くろいメガネ",
  "くろおび",
  "こうかくレンズ",
  "こだわりスカーフ",
  "さらさらいわ",
  "じしゃく",
  "しめったいわ",
  "シュカのみ",
  "シルクのスカーフ",
  "しろいハーブ",
  "しんぴのしずく",
  "するどいくちばし",
  "せんせいのツメ",
  "ソクノのみ",
  "たつじんのおび",
  "たべのこし",
  "タンガのみ",
  "ちからのハチマキ",
  "つめたいいわ",
  "でんきだま",
  "どくバリ",
  "とけないこおり",
  "とつげきチョッキ",
  "ナモのみ",
  "のろいのおふだ",
  "バコウのみ",
  "ハバンのみ",
  "ビアーのみ",
  "ひかりのこな",
  "ひかりのねんど",
  "ヒメリのみ",
  "ピントレンズ",
  "フォーカスレンズ",
  "ホズのみ",
  "まがったスプーン",
  "メタルコート",
  "メトロノーム",
  "メンタルハーブ",
  "もくたん",
  "ものしりメガネ",
  "ヤチェのみ",
  "やわらかいすな",
  "ようせいのハネ",
  "ヨプのみ",
  "ヨロギのみ",
  "ラムのみ",
  "りゅうのキバ",
  "リリバのみ",
  "リンドのみ",
  "ロゼルのみ",
] as const

export type ChampionsItem = typeof CHAMPIONS_ITEM_OPTIONS[number]

export const CHAMPIONS_ITEM_LABEL_KO: Partial<Record<ChampionsItem, string>> = {
  "あついいわ": "이상한플레이트",
  "イトケのみ": "의문열매",
  "いのちのたま": "파워앵클릿",
  "ウタンのみ": "학습장치",
  "おうじゃのしるし": "예리한부리",
  "おおきなねっこ": "행운의향로",
  "オッカのみ": "스타열매",
  "オボンのみ": "슈박열매",
  "オレンのみ": "노멜열매",
  "かいがらのすず": "포커스렌즈",
  "カゴのみ": "또뽀열매",
  "カシブのみ": "멘탈허브",
  "かたいいし": "파랑밴드",
  "きあいのタスキ": "불구슬플레이트",
  "きあいのハチマキ": "조개껍질방울",
  "キーのみ": "메호키열매",
  "きせきのタネ": "분홍밴드",
  "きれいなぬけがら": "꽃향로",
  "ぎんのこな": "독바늘",
  "くろいてっきゅう": "초록플레이트",
  "くろいメガネ": "초록밴드",
  "くろおび": "노랑밴드",
  "こうかくレンズ": "끈적끈적바늘",
  "こだわりスカーフ": "원령플레이트",
  "さらさらいわ": "푸른하늘플레이트",
  "じしゃく": "광각렌즈",
  "しめったいわ": "비단벌레플레이트",
  "シュカのみ": "하양허브",
  "シルクのスカーフ": "스피드파우더",
  "しろいハーブ": "부드러운모래",
  "しんぴのしずく": "힘의머리띠",
  "するどいくちばし": "박식안경",
  "せんせいのツメ": "검은안경",
  "ソクノのみ": "미클열매",
  "たつじんのおび": "파워렌즈",
  "たべのこし": "금속파우더",
  "タンガのみ": "선제공격손톱",
  "ちからのハチマキ": "파워리스트",
  "つめたいいわ": "대지플레이트",
  "でんきだま": "대파",
  "どくバリ": "달인의띠",
  "とけないこおり": "빛의점토",
  "とつげきチョッキ": "돌격조끼",
  "ナモのみ": "왕의징표석",
  "のろいのおふだ": "생명의구슬",
  "バコウのみ": "교정깁스",
  "ハバンのみ": "구애머리띠",
  "ビアーのみ": "반짝가루",
  "ひかりのこな": "전기구슬",
  "ひかりのねんど": "파워밴드",
  "ヒメリのみ": "라부탐열매",
  "ピントレンズ": "무사태평향로",
  "フォーカスレンズ": "물방울플레이트",
  "ホズのみ": "부적금화",
  "まがったスプーン": "파워풀허브",
  "メタルコート": "럭키펀치",
  "メトロノーム": "우뢰플레이트",
  "メンタルハーブ": "자석",
  "もくたん": "맹독구슬",
  "ものしりメガネ": "파워벨트",
  "ヤチェのみ": "자보열매",
  "やわらかいすな": "빨강밴드",
  "ようせいのハネ": "요정의깃털",
  "ヨプのみ": "애터열매",
  "ヨロギのみ": "평온의방울",
  "ラムのみ": "자야열매",
  "りゅうのキバ": "화염구슬",
  "リリバのみ": "은빛가루",
  "リンドのみ": "애슈열매",
  "ロゼルのみ": "휘핑팝",
}

export const CHAMPIONS_ITEM_LABEL_EN: Partial<Record<ChampionsItem, string>> = {
  "あついいわ": "Mind Plate",
  "イトケのみ": "Enigma Berry",
  "いのちのたま": "Power Anklet",
  "ウタンのみ": "Exp. Share",
  "おうじゃのしるし": "Sharp Beak",
  "おおきなねっこ": "Luck Incense",
  "オッカのみ": "Starf Berry",
  "オボンのみ": "Watmel Berry",
  "オレンのみ": "Nomel Berry",
  "かいがらのすず": "Zoom Lens",
  "カゴのみ": "Grepa Berry",
  "カシブのみ": "Mental Herb",
  "かたいいし": "Blue Scarf",
  "きあいのタスキ": "Flame Plate",
  "きあいのハチマキ": "Shell Bell",
  "キーのみ": "Spelon Berry",
  "きせきのタネ": "Pink Scarf",
  "きれいなぬけがら": "Rose Incense",
  "ぎんのこな": "Poison Barb",
  "くろいてっきゅう": "Meadow Plate",
  "くろいメガネ": "Green Scarf",
  "くろおび": "Yellow Scarf",
  "こうかくレンズ": "Sticky Barb",
  "こだわりスカーフ": "Spooky Plate",
  "さらさらいわ": "Sky Plate",
  "じしゃく": "Wide Lens",
  "しめったいわ": "Insect Plate",
  "シュカのみ": "White Herb",
  "シルクのスカーフ": "Quick Powder",
  "しろいハーブ": "Soft Sand",
  "しんぴのしずく": "Muscle Band",
  "するどいくちばし": "Wise Glasses",
  "せんせいのツメ": "Black Glasses",
  "ソクノのみ": "Micle Berry",
  "たつじんのおび": "Power Lens",
  "たべのこし": "Metal Powder",
  "タンガのみ": "Quick Claw",
  "ちからのハチマキ": "Power Bracer",
  "つめたいいわ": "Earth Plate",
  "でんきだま": "Leek",
  "どくバリ": "Expert Belt",
  "とけないこおり": "Light Clay",
  "とつげきチョッキ": "Assault Vest",
  "ナモのみ": "King’s Rock",
  "のろいのおふだ": "Life Orb",
  "バコウのみ": "Macho Brace",
  "ハバンのみ": "Choice Band",
  "ビアーのみ": "Bright Powder",
  "ひかりのこな": "Light Ball",
  "ひかりのねんど": "Power Band",
  "ヒメリのみ": "Rabuta Berry",
  "ピントレンズ": "Lax Incense",
  "フォーカスレンズ": "Splash Plate",
  "ホズのみ": "Amulet Coin",
  "まがったスプーン": "Power Herb",
  "メタルコート": "Lucky Punch",
  "メトロノーム": "Zap Plate",
  "メンタルハーブ": "Magnet",
  "もくたん": "Toxic Orb",
  "ものしりメガネ": "Power Belt",
  "ヤチェのみ": "Jaboca Berry",
  "やわらかいすな": "Red Scarf",
  "ようせいのハネ": "Fairy Feather",
  "ヨプのみ": "Rowap Berry",
  "ヨロギのみ": "Soothe Bell",
  "ラムのみ": "Pamtre Berry",
  "りゅうのキバ": "Flame Orb",
  "リリバのみ": "Silver Powder",
  "リンドのみ": "Custap Berry",
  "ロゼルのみ": "Whipped Dream",
}

export const CHAMPIONS_ITEM_ALIASES: Partial<Record<ChampionsItem, string[]>> = {
  "あついいわ": ["이상한플레이트", "Mind Plate"],
  "イトケのみ": ["의문열매", "Enigma Berry"],
  "いのちのたま": ["파워앵클릿", "Power Anklet"],
  "ウタンのみ": ["학습장치", "Exp. Share"],
  "おうじゃのしるし": ["예리한부리", "Sharp Beak"],
  "おおきなねっこ": ["행운의향로", "Luck Incense"],
  "オッカのみ": ["스타열매", "Starf Berry"],
  "オボンのみ": ["슈박열매", "Watmel Berry"],
  "オレンのみ": ["노멜열매", "Nomel Berry"],
  "かいがらのすず": ["포커스렌즈", "Zoom Lens"],
  "カゴのみ": ["또뽀열매", "Grepa Berry"],
  "カシブのみ": ["멘탈허브", "Mental Herb"],
  "かたいいし": ["파랑밴드", "Blue Scarf"],
  "きあいのタスキ": ["기띠", "띠", "불구슬플레이트", "Flame Plate"],
  "きあいのハチマキ": ["조개껍질방울", "Shell Bell"],
  "キーのみ": ["메호키열매", "Spelon Berry"],
  "きせきのタネ": ["분홍밴드", "Pink Scarf"],
  "きれいなぬけがら": ["꽃향로", "Rose Incense"],
  "ぎんのこな": ["독바늘", "Poison Barb"],
  "くろいてっきゅう": ["초록플레이트", "Meadow Plate"],
  "くろいメガネ": ["초록밴드", "Green Scarf"],
  "くろおび": ["노랑밴드", "Yellow Scarf"],
  "こうかくレンズ": ["끈적끈적바늘", "Sticky Barb"],
  "こだわりスカーフ": ["스카프", "원령플레이트", "Spooky Plate"],
  "さらさらいわ": ["푸른하늘플레이트", "Sky Plate"],
  "じしゃく": ["광각렌즈", "Wide Lens"],
  "しめったいわ": ["비단벌레플레이트", "Insect Plate"],
  "シュカのみ": ["하양허브", "White Herb"],
  "シルクのスカーフ": ["스피드파우더", "Quick Powder"],
  "しろいハーブ": ["부드러운모래", "Soft Sand"],
  "しんぴのしずく": ["힘의머리띠", "Muscle Band"],
  "するどいくちばし": ["박식안경", "Wise Glasses"],
  "せんせいのツメ": ["검은안경", "Black Glasses"],
  "ソクノのみ": ["미클열매", "Micle Berry"],
  "たつじんのおび": ["파워렌즈", "Power Lens"],
  "たべのこし": ["금속파우더", "남은음식", "먹밥", "Metal Powder"],
  "タンガのみ": ["선제공격손톱", "Quick Claw"],
  "ちからのハチマキ": ["파워리스트", "Power Bracer"],
  "つめたいいわ": ["대지플레이트", "Earth Plate"],
  "でんきだま": ["대파", "Leek"],
  "どくバリ": ["달인의띠", "Expert Belt"],
  "とけないこおり": ["빛의점토", "Light Clay"],
  "とつげきチョッキ": ["돌격조끼", "Assault Vest"],
  "ナモのみ": ["왕의징표석", "King’s Rock"],
  "のろいのおふだ": ["생명의구슬", "Life Orb"],
  "バコウのみ": ["교정깁스", "Macho Brace"],
  "ハバンのみ": ["구애머리띠", "Choice Band"],
  "ビアーのみ": ["반짝가루", "Bright Powder"],
  "ひかりのこな": ["반짝가루", "전기구슬", "Light Ball"],
  "ひかりのねんど": ["파워밴드", "Power Band"],
  "ヒメリのみ": ["라부탐열매", "Rabuta Berry"],
  "ピントレンズ": ["무사태평향로", "Lax Incense"],
  "フォーカスレンズ": ["물방울플레이트", "Splash Plate"],
  "ホズのみ": ["부적금화", "Amulet Coin"],
  "まがったスプーン": ["파워풀허브", "Power Herb"],
  "メタルコート": ["금속코트", "럭키펀치", "Lucky Punch"],
  "メトロノーム": ["우뢰플레이트", "Zap Plate"],
  "メンタルハーブ": ["멘탈허브", "자석", "Magnet"],
  "もくたん": ["맹독구슬", "Toxic Orb"],
  "ものしりメガネ": ["파워벨트", "Power Belt"],
  "ヤチェのみ": ["자보열매", "Jaboca Berry"],
  "やわらかいすな": ["빨강밴드", "Red Scarf"],
  "ようせいのハネ": ["요정의깃털", "Fairy Feather"],
  "ヨプのみ": ["애터열매", "Rowap Berry"],
  "ヨロギのみ": ["평온의방울", "Soothe Bell"],
  "ラムのみ": ["자야열매", "Pamtre Berry"],
  "りゅうのキバ": ["화염구슬", "Flame Orb"],
  "リリバのみ": ["은빛가루", "Silver Powder"],
  "リンドのみ": ["애슈열매", "Custap Berry"],
  "ロゼルのみ": ["휘핑팝", "Whipped Dream"],
}

export const CHAMPIONS_ITEM_SPRITE_MAP: Partial<Record<ChampionsItem, string>> = {
  "あついいわ": "mind-plate",
  "イトケのみ": "enigma-berry",
  "いのちのたま": "power-anklet",
  "ウタンのみ": "exp-share",
  "おうじゃのしるし": "sharp-beak",
  "おおきなねっこ": "luck-incense",
  "オッカのみ": "starf-berry",
  "オボンのみ": "watmel-berry",
  "オレンのみ": "nomel-berry",
  "かいがらのすず": "zoom-lens",
  "カゴのみ": "grepa-berry",
  "カシブのみ": "mental-herb",
  "かたいいし": "blue-scarf",
  "きあいのタスキ": "flame-plate",
  "きあいのハチマキ": "shell-bell",
  "キーのみ": "spelon-berry",
  "きせきのタネ": "pink-scarf",
  "きれいなぬけがら": "rose-incense",
  "ぎんのこな": "poison-barb",
  "くろいてっきゅう": "meadow-plate",
  "くろいメガネ": "green-scarf",
  "くろおび": "yellow-scarf",
  "こうかくレンズ": "sticky-barb",
  "こだわりスカーフ": "item-sprites/choice-scarf.png",
  "さらさらいわ": "sky-plate",
  "じしゃく": "wide-lens",
  "しめったいわ": "insect-plate",
  "シュカのみ": "white-herb",
  "シルクのスカーフ": "quick-powder",
  "しろいハーブ": "soft-sand",
  "しんぴのしずく": "muscle-band",
  "するどいくちばし": "wise-glasses",
  "せんせいのツメ": "black-glasses",
  "ソクノのみ": "micle-berry",
  "たつじんのおび": "power-lens",
  "たべのこし": "metal-powder",
  "タンガのみ": "quick-claw",
  "ちからのハチマキ": "power-bracer",
  "つめたいいわ": "earth-plate",
  "でんきだま": "stick",
  "どくバリ": "expert-belt",
  "とけないこおり": "light-clay",
  "とつげきチョッキ": "assault-vest",
  "ナモのみ": "kings-rock",
  "のろいのおふだ": "life-orb",
  "バコウのみ": "macho-brace",
  "ハバンのみ": "choice-band",
  "ビアーのみ": "bright-powder",
  "ひかりのこな": "light-ball",
  "ひかりのねんど": "power-band",
  "ヒメリのみ": "rabuta-berry",
  "ピントレンズ": "lax-incense",
  "フォーカスレンズ": "splash-plate",
  "ホズのみ": "amulet-coin",
  "まがったスプーン": "power-herb",
  "メタルコート": "lucky-punch",
  "メトロノーム": "zap-plate",
  "メンタルハーブ": "magnet",
  "もくたん": "toxic-orb",
  "ものしりメガネ": "power-belt",
  "ヤチェのみ": "jaboca-berry",
  "やわらかいすな": "red-scarf",
  "ようせいのハネ": "item-sprites/fairy-feather.png",
  "ヨプのみ": "rowap-berry",
  "ヨロギのみ": "soothe-bell",
  "ラムのみ": "pamtre-berry",
  "りゅうのキバ": "flame-orb",
  "リリバのみ": "silver-powder",
  "リンドのみ": "custap-berry",
  "ロゼルのみ": "whipped-dream",
}

export function localizedChampionsItemLabel(item: string, language: 'ko' | 'en' | 'ja' = 'ko') {
  if (language === 'ja') return item
  if (language === 'ko') return CHAMPIONS_ITEM_LABEL_KO[item as ChampionsItem] ?? item
  return CHAMPIONS_ITEM_LABEL_EN[item as ChampionsItem] ?? CHAMPIONS_ITEM_LABEL_KO[item as ChampionsItem] ?? item
}
