export const CHAMPIONS_ITEM_OPTIONS = [
  "イトケのみ",
  "おうじゃのしるし",
  "オッカのみ",
  "オボンのみ",
  "カゴのみ",
  "カシブのみ",
  "きあいのタスキ",
  "きせきのタネ",
  "くろいメガネ",
  "くろおび",
  "こだわりスカーフ",
  "じしゃく",
  "シュカのみ",
  "シルクのスカーフ",
  "しろいハーブ",
  "しんぴのしずく",
  "するどいくちばし",
  "せんせいのツメ",
  "ソクノのみ",
  "たべのこし",
  "でんきだま",
  "どくバリ",
  "とけないこおり",
  "ナモのみ",
  "のろいのおふだ",
  "バコウのみ",
  "ハバンのみ",
  "ビアーのみ",
  "ひかりのこな",
  "ピントレンズ",
  "まがったスプーン",
  "メタルコート",
  "メンタルハーブ",
  "もくたん",
  "ヤチェのみ",
  "やわらかいすな",
  "ようせいのハネ",
  "ヨプのみ",
  "ヨロギのみ",
  "ラムのみ",
  "りゅうのキバ",
  "リリバのみ",
  "リンドのみ",
  "ロゼルのみ",
] as const

export type ChampionsItem = typeof CHAMPIONS_ITEM_OPTIONS[number]

export const CHAMPIONS_ITEM_ALIASES: Partial<Record<ChampionsItem, string[]>> = {}

export const CHAMPIONS_ITEM_SPRITE_MAP: Partial<Record<ChampionsItem, string>> = {
  "きあいのタスキ": "focus-sash",
  "こだわりスカーフ": "choice-scarf",
  "たべのこし": "leftovers",
  "ひかりのこな": "bright-powder",
  "メタルコート": "metal-coat",
  "メンタルハーブ": "mental-herb",
  "オッカのみ": "occa-berry",
  "ヤチェのみ": "yache-berry",
  "ロゼルのみ": "roseli-berry",
}
